## Tensors

### Scalars (Rank 0 Tensors)

In [4]:
x = 25
y = 3
type(x)

int

In [5]:
xy_sum = x + y
type(xy_sum)

int

In [6]:
xy_sum

28

In [7]:
x_float = 25.0

In [8]:
xy_float = x_float + y

In [9]:
xy_float

28.0

In [10]:
type(xy_float)

float

#### Scalars in Pytorch

In [14]:
import torch

In [16]:
x_pt = torch.tensor(25)
x_pt

tensor(25)

In [17]:
x_pt.shape # Shape is the dimension of x_pt, i.e, 1-D meaning it is a rank-0 scalar

torch.Size([])

#### Scalars in TensorFlow

In [19]:
import tensorflow as tf

In [25]:
x_tf = tf.Variable(25, dtype=tf.int16) # dtype is optional
# tf.Variable is the equivalent of torch.tensor but gives a complicated output
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [26]:
x_tf.shape # Equivalent of torch.shape

TensorShape([])

In [30]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [31]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [34]:
sum_tf = tf.add(x_tf, y_tf) # Add functionality of the tensorflow module
sum_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [36]:
sum_tf.numpy()

np.int16(28)

In [37]:
type(sum_tf.numpy())

numpy.int16

In [39]:
tf_float = tf.Variable(25., dtype=tf.float16) # To Remember: how we have mentioned 25 as 25.
tf_float

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>

### Vectors (Rank 1 Tensors)

In [1]:
import numpy as np

In [11]:
x = np.array([25, 3, 7]) # type argument is optional, e.g.: dtype=np.float16
x

array([25,  3,  7])

In [3]:
len(x)

3

In [4]:
type(x)

numpy.ndarray

In [5]:
x.shape

(3,)

In [6]:
x[0]

np.int64(25)

In [9]:
type(x[0])

numpy.int64

#### Vector Transposition

In [12]:
# Transposing a 1-D array has no effect
x_t = x.T
x_t

array([25,  3,  7])

In [13]:
x_t.shape

(3,)

In [14]:
# but it does when we use nested "matrix-style" brackets:
y = np.array([[25, 3, 7]])
y

array([[25,  3,  7]])

In [15]:
y.shape

(1, 3)

In [16]:
y_t = y.T
y_t

array([[25],
       [ 3],
       [ 7]])

In [17]:
y_t.shape

(3, 1)

In [18]:
y_t.T

array([[25,  3,  7]])

In [19]:
y_t.T.shape

(1, 3)

#### Zero Vectors

In [21]:
# Have no effect if added to another vector
z = np.zeros(3)
z

array([0., 0., 0.])

#### Vectors in PyTorch and TensorFlow

In [23]:
import torch

In [24]:
x_pt = torch.tensor([25, 3, 7])
x_pt

tensor([25,  3,  7])

In [25]:
import tensorflow as tf

In [26]:
x_tf = tf.Variable([25, 3, 7])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  3,  7], dtype=int32)>